helpingyou-project/course/urls.py
from django.urls import path

from .views import * 

app_name = 'course'
urlpatterns = [
        path('', course, name='course'),
        path('instructor/quiz/', InstructorQuizListView.as_view(), name='quiz_change_list'),
        path('instructor/quiz/add/', QuizCreateView.as_view(), name='quiz_add'),
        path('instructor/quiz/<int:pk>/', QuizUpdateView.as_view(), name='quiz_change'),
        path('instructor/quiz/<int:pk>/delete/', QuizDeleteView.as_view(), name='quiz_delete'),
        path('instructor/quiz/<int:pk>/results/', QuizResultsView.as_view(), name='quiz_results'),
        path('instructor/quiz/<int:pk>/question/add/', question_add, name='question_add'),
        path('instructor/quiz/<int:quiz_pk>/question/<int:question_pk>/', question_change, name='question_change'),
        path('instructor/quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', QuestionDeleteView.as_view(), name='question_delete'),
        path('student/quiz/', StudentQuizListView.as_view(), name='quiz_list'),
        path('student/taken/', TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('student/quiz/<int:pk>/', take_quiz, name='take_quiz'),
    
]

helpingyou-project/helpingYou/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from user import views as user_views
from course import views as course_views
from jobs import views as job_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('signup/', user_views.SignUpView.as_view(), name='signup'),
    path('signup/student/', user_views.StudentSignUpView.as_view(), name='student_signup'),
    path('signup/instructor/', user_views.InstructorSignUpView.as_view(), name='instructor_signup'),
    path('signup/recruiter/', user_views.RecruiterSignUpView.as_view(), name='recruiter_signup'),
    url(r'^user/update/(?P<pk>[\-\w]+)/$', user_views.edit_user, name='profile_update'),
    path('dashboard/', course_views.dashboard, name='dashboard'),
    path('course/<int:c_pk>/',include('course.urls', namespace='course')),
    path('', user_views.home, name='home'),
    path('jobs/', job_view.job, name='job'),
    path('jobs/listing/', job_view.job_listing_page, name='job_listing'),

]

helpingyou-project/course/models.py
from django.db import models
from django.utils.html import escape, mark_safe
from user.models import * 

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)

class Quiz(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='quizzes')

    def __str__(self):
        return self.name

class Videos(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='videos')
    name = models.CharField(max_length=255)
    url = models.URLField()
    subject = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='videos')
    transcript = models.TextField(default ="")

    def __str__(self):
        return self.name

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.CharField('Question', max_length=255)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    enrolled_courses = models.ManyToManyField(Course, related_name='enrolled_courses')

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username

def create_student(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        course_profile = Student(user=user)
        course_profile.save()
post_save.connect(create_student, sender=User)

class TakenQuiz(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')

helpingyou-project/course/forms.py
from django.forms import ModelForm, IntegerField
from .models import *
from django.db import transaction
from user.models import UserProfile
from django import forms


class EnrollForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EnrollForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['readonly'] = True

    class Meta:
        model = Course
        fields = ['name',]
    course_id = forms.IntegerField(widget = forms.HiddenInput(), required = False)


class CourseRegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CourseRegisterForm, self).__init__(*args, **kwargs)
        
    class Meta:
        model = Course
        fields = ['name',]


class VideosForm(forms.ModelForm):
    class Meta:
        model = Videos
        fields = ['name','url',]


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )

class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')

helpingyou-project/course/views.py
from django.shortcuts import HttpResponseRedirect,render, redirect, get_object_or_404
from  django.forms import formset_factory
from .forms import *
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from user.decorators import student_required, instructor_required
from django.contrib import messages
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,UpdateView)
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.db.models import Count, Avg
from django.forms import inlineformset_factory
from user.models import User
from .models import *
from speech2text.speech2text import transcription
from jobs.views import job as job

@login_required
def dashboard(request):
    user = User.objects.get(id=request.user.id)
    if user.is_student:
        return student_dashboard(request)
    else:
        if user.is_instructor:
            return instructor_dashboard(request)
        else:
            if user.is_recruiter:
                return job(request)
            else:
                return HttpResponseRedirect('/login')

@login_required
@student_required
def student_dashboard(request):
    user_profile = Student.objects.get(user_id=request.user.id)
    enrolled_course = user_profile.enrolled_courses.all().values_list('name', flat=True)
    available_courses = list(Course.objects.exclude(name__in=enrolled_course).values_list('name', flat=True))
    #print("enrolled_course -------- ",enrolled_course)
    #print("available_courses ------- ", available_courses)
    available_formset = []
    enrolled_formset = []
    for course in available_courses:
        available_formset.append(EnrollForm(initial={"name":course},prefix=course))
    for course in enrolled_course:
        enrolled_formset.append(EnrollForm(initial={"name":course, "course_id": Course.objects.get(name=course).pk },prefix=course))
    if request.method == 'POST':
        course = list(request.POST)[1].split("-")[0]
        available_form = EnrollForm(request.POST, prefix=course)
        if available_form.is_valid() and course in available_courses:
            name = available_form.cleaned_data["name"]
            request_enroll = Course.objects.get(name=name)
            user_profile.enrolled_courses.add(request_enroll)
            return HttpResponseRedirect('/course/{}'.format(request_enroll.pk))
        enrolled_form = EnrollForm(request.POST, prefix=course)
        if enrolled_form.is_valid() and course in enrolled_course:
            name=enrolled_form.cleaned_data["name"]
            request_unenroll = Course.objects.get(name=name)
            user_profile.enrolled_courses.remove(request_unenroll)
            messages.success(request, 'Successfully unenrolled from course ', name)
            return HttpResponseRedirect('/dashboard')
    return render(request, "course/dashboard.html", {"available_formset":available_formset, "enrolled_formset":enrolled_formset })

@login_required
@instructor_required
def instructor_dashboard(request):
    user_profile = Student.objects.get(user_id=request.user.id)
    enrolled_course = user_profile.enrolled_courses.all()
    form = CourseRegisterForm()
    if request.method == "POST":
        form = CourseRegisterForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data["name"]
            if not Course.objects.filter(name=name).exists():
                user_profile.enrolled_courses.create(name=name)
                messages.success(request,"Course created")
                return HttpResponseRedirect('/dashboard')
            else:
                messages.success(request,"Course with same name exists")
                return HttpResponseRedirect('/dashboard')
    return render(request, 'course/dashboard.html', {"form":form, "enrolled_course":enrolled_course})


@login_required
def course(request,c_pk):
    user = User.objects.get(id=request.user.id)
    if user.is_student:
        return student_course(request,c_pk)
    else:
        if user.is_instructor:
            return instructor_course(request,c_pk)
        else:
            return HttpResponseRedirect('/login')

@login_required
@student_required
def student_course(request,c_pk):
    course_name = Course.objects.get(id=c_pk)
    all_videos = Videos.objects.filter(subject_id=c_pk)
    return render(request, "course/course.html", {"c_pk": c_pk, "course": course_name, "all_videos":all_videos})


@login_required
@instructor_required
def instructor_course(request,c_pk):
    course_name = Course.objects.get(id=c_pk)
    all_current_videos = Videos.objects.filter(owner_id=request.user.id).filter(subject_id=c_pk)
    video_form = VideosForm()
    if request.method == "POST":
        form = VideosForm(request.POST)
        if form.is_valid():
            video = form.save(commit=False)
            name = form.cleaned_data["name"]
            url = form.cleaned_data["url"]
            transcription(name,url)
            file1= open("transcript_"+name+".txt","r+")
            transcript = file1.read()
            video.owner_id = request.user.id
            video.subject_id = c_pk
            video.transcript = transcript
            video.save()
            messages.success(request,"Video added")
            return HttpResponseRedirect('/course/{}'.format(c_pk))
    return render(request, "course/course.html", {"c_pk": c_pk, "course": course_name, "video_form":video_form, "all_current_videos":all_current_videos})




@method_decorator([login_required, instructor_required], name='dispatch')
class InstructorQuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'course/quiz_change_list.html'

    def get_queryset(self):
        queryset = self.request.user.quizzes \
            .select_related('course') \
            .annotate(questions_count=Count('questions', distinct=True)) \
            .annotate(taken_count=Count('taken_quizzes', distinct=True))
        queryset = queryset.filter(course_id=self.request.path.split("/")[2])
        return queryset


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizCreateView(CreateView):
    model = Quiz
    fields = ('name',)
    template_name = 'course/quiz_add_form.html'

    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.owner = self.request.user
        quiz.course = Course.objects.get(id=self.request.path.split("/")[2])
        quiz.save()
        messages.success(self.request, 'The quiz was created with success! Go ahead and add some questions now.')
        return redirect('course:quiz_change', self.request.path.split("/")[2], quiz.pk)


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizUpdateView(UpdateView):
    model = Quiz
    fields = ('name', )
    context_object_name = 'quiz'
    template_name = 'course/quiz_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.quizzes.all()

    def get_success_url(self):
        return reverse('course:quiz_change', kwargs={'pk': self.object.pk, 'c_pk': self.request.path.split("/")[2]})


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizDeleteView(DeleteView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'course/quiz_delete_confirm.html'

    def get_success_url(self):
        c_pk = self.kwargs['c_pk']
        print(c_pk)
        return reverse_lazy('course:quiz_change_list', kwargs={'c_pk': self.request.path.split("/")[2]})

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(request, 'The quiz %s was deleted with success!' % quiz.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizResultsView(DetailView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'course/quiz_results.html'

    def get_context_data(self, **kwargs):
        quiz = self.get_object()
        taken_quizzes = quiz.taken_quizzes.select_related('student__user').order_by('-date')
        total_taken_quizzes = taken_quizzes.count()
        quiz_score = quiz.taken_quizzes.aggregate(average_score=Avg('score'))
        extra_context = {
            'taken_quizzes': taken_quizzes,
            'total_taken_quizzes': total_taken_quizzes,
            'quiz_score': quiz_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()

@login_required
@instructor_required
def question_add(request,c_pk, pk):
    # By filtering the quiz by the url keyword argument `pk` and
    # by the owner, which is the logged in user, we are protecting
    # this view at the object-level. Meaning only the owner of
    # quiz will be able to add questions to it.
    print(c_pk)
    quiz = get_object_or_404(Quiz, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('course:question_change', c_pk, quiz.pk, question.pk)
    else:
        form = QuestionForm()

helpingyou-project/course/templates/course/course.html
<!-- templates/course/course.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<h4> Welcome to course -- {{course}}</h4>
{% if user.is_authenticated %}

{% if user.is_student %}

<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert"></div>
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'course:course' c_pk%}">Videos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'course:quiz_list' c_pk %}">Quiz</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'course:taken_quiz_list' c_pk %}">Grades</a>
    </li>
  </ul>

  {% for videos in all_videos%}
  {{ videos.url}}
<details>
    <summary>View Transcript</summary>

  {{ videos.transcript}}
</details>
  <br>

  {% endfor %}
{% elif user.is_instructor %}

<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert"></div>
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'course:course' c_pk%}">Videos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'course:quiz_change_list' c_pk %}">Quiz</a>
    </li>
  </ul>


  {{all_current_videos}}
  <hr> Add Videos<br>
  <form method="post">
      {%csrf_token%}
      {{video_form}}
      <input type="submit" class="btn btn-dark btn-lg" value="Post a video">
      <hr>

  </form>













{% else %}

{% endif %}

{% endif %}
{% endblock %}

helpingyou-project/course/templates/course/quiz_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load filter_tags%}

{% block content %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert"></div>
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link " href="{% url 'course:course' request.path|split:'/'|getValue:'2'%}">Videos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'course:quiz_change_list' request.path|split:'/'|getValue:'2' %}">Quiz</a>
    </li>
  </ul>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'course:quiz_change_list' request.path|split:'/'|getValue:'2' %}">My Quizzes</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ quiz.name }}
    <a href="{% url 'course:quiz_results' request.path|split:'/'|getValue:'2' quiz.pk %}" class="btn btn-primary float-right">View results</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'course:quiz_change_list' request.path|split:'/'|getValue:'2' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
        <a href="{% url 'course:quiz_delete' request.path|split:'/'|getValue:'2' quiz.pk %}" class="btn btn-danger float-right">Delete</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Questions</strong>
        </div>
        <div class="col-2">
          <strong>Answers</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'course:question_change' request.path|split:'/'|getValue:'2' quiz.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'course:question_add' request.path|split:'/'|getValue:'2' quiz.pk %}">add the first question</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'course:question_add' request.path|split:'/'|getValue:'2' quiz.pk %}" class="btn btn-primary btn-sm">Add question</a>
    </div>
  </div>
{% endblock %}

helpingyou-project/course/templates/course/quiz_change_list.html
{% extends 'base.html' %}

{% block content %}
{% load filter_tags%}

<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert"></div>
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link " href="{% url 'course:course' request.path|split:'/'|getValue:'2'%}">Videos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'course:quiz_change_list' request.path|split:'/'|getValue:'2' %}">Quiz</a>
    </li>
  </ul>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Quizzes</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Quizzes</h2>
  <a href="{% url 'course:quiz_add' request.path|split:'/'|getValue:'2' %}" class="btn btn-primary mb-3" role="button">Add quiz</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Questions</th>
          <th>Taken</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle"><a href="{% url 'course:quiz_change'  request.path|split:'/'|getValue:'2' quiz.pk %}">{{ quiz.name }}</a></td>
            <td class="align-middle">{{ quiz.course.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }}</td>
            <td class="align-middle">{{ quiz.taken_count }}</td>
            <td class="text-right">
              <a href="{% url 'course:quiz_results'  request.path|split:'/'|getValue:'2' quiz.pk %}" class="btn btn-primary">View results</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

helpingyou-project/course/templates/course/quiz_list.html
{% extends 'base.html' %}
{% load filter_tags%}

{% block content %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert"></div>
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'course:course' request.path|split:'/'|getValue:'2'%}">Videos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'course:quiz_list' request.path|split:'/'|getValue:'2' %}">Quiz</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'course:taken_quiz_list' request.path|split:'/'|getValue:'2' %}">Grades</a>
    </li>
  </ul>

  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Length</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.course.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }} questions</td>
            <td class="text-right">
              <a href="{% url 'course:take_quiz' request.path|split:'/'|getValue:'2' quiz.pk %}" class="btn btn-primary">Start quiz</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No quiz matching your interests right now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

helpingyou-project/course/templates/course/take_quiz_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load filter_tags%}

{% block content %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert"></div>
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link " href="{% url 'course:course' request.path|split:'/'|getValue:'2'%}">Videos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'course:quiz_list' request.path|split:'/'|getValue:'2' %}">Quiz</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'course:taken_quiz_list' request.path|split:'/'|getValue:'2' %}">Grades</a>
    </li>
  </ul>

  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
  </div>
  <h2 class="mb-3">{{ quiz.name }}</h2>
  <p class="lead">{{ question.text }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Next →</button>
  </form>
{% endblock %}

helpingyou-project/course/templates/course/taken_quiz_list.html
{% extends 'base.html' %}
{% load filter_tags%}

{% block content %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert"></div>
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link " href="{% url 'course:course' request.path|split:'/'|getValue:'2'%}">Videos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link  " href="{% url 'course:quiz_list' request.path|split:'/'|getValue:'2' %}">Quiz</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'course:taken_quiz_list' request.path|split:'/'|getValue:'2' %}">Grades</a>
    </li>
  </ul>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td>{{ taken_quiz.quiz.name }}</td>
            <td>{{ taken_quiz.quiz.course.get_html_badge }}</td>
            <td>{{ taken_quiz.score }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't completed any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}